project:
  type: website

website:
  title: "Data Hack-a-thon and Visualization Event"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: page1.qmd
        text: Sheffield

  page-footer: "University of Sheffield"

format:
  html:
    theme: cosmo
    toc: true
